### ISSUE TITLE
About International Version

### ISSUE THREAD

**Issue by ilikecola** [cytoscape/cytoscape#11]
Hello,
I wonder if Cytoscape can develop international version like Chinese , Japanese.
If possible, may I join the project and make help on internationalize?

Thanks.

Zhang

**Comment by AdamStuart** [comment]
Zhang,

The node and edge labels should work across UTF-8 character sets.   (Here's an [example)](https://publications.nigms.nih.gov/computinglife/cytoscape.htm)

Unfortunately, you're going to have to fork the project to get real internationalization.

Cytoscape made a English-only decision at the 3.0 milestone, and commands, attributes etc are hardcoded strings throughout.  Support of other languages will likely be reconsidered in a 4.0 version, but there is no such version foreseen at this point.
