### ISSUE TITLE
Source code can not be found

### ISSUE THREAD

**Issue by pisful** [cytoscape/cytoscape#14]
Can you tell me where I crossed the bottom of that jar?
![1](https://user-images.githubusercontent.com/19769904/33116593-4fcacdb4-cfa0-11e7-9eb2-e7b53e4d3f23.png)
![2](https://user-images.githubusercontent.com/19769904/33116605-5e394b28-cfa0-11e7-9ead-887bceeed33e.png)

**Comment by AlexanderPico** [comment]
Unfortunately, this is a limitation of Java Swing, which Cytoscape depends upon but does not directly develop.
