### ISSUE TITLE
Add a 'File --> close' option in the menu bar (suggestion)

### ISSUE THREAD

**Issue by veroniquevoisin** [cytoscape/cytoscape#15]
When I work on a new network and I want to close my session that became messy, I have to do 'File New --> Session' . It is not intuitive for new user. A "close" option seems more intuitive (closing before importing/starting a new one). 
![screen shot 2018-01-11 at 3 31 43 pm](https://user-images.githubusercontent.com/7570379/34846073-f246c208-f6e4-11e7-8468-87df28eafe33.png)

**Comment by AlexanderPico** [comment]
I agree! In the R package we're working on, the function is called closeSession()   :) 

I've posted this as a feature request to update the File menu and include a "Close" menu item:
http://code.cytoscape.org/redmine/issues/4111
