### ISSUE TITLE
Cytoscape 3.6.0: issue zooming in and out using laptop trackpad

### ISSUE THREAD

**Issue by veroniquevoisin** [cytoscape/cytoscape#16]
Cytoscape 6.0: issue zooming in and out using laptop trackpad

**Comment by AlexanderPico** [comment]
Thanks for reporting. We're tracking this issue on redmine: http://code.cytoscape.org/redmine/issues/4086

**Comment by JulianKingman** [comment]
Same issue here, OSX high sierra 10.13.3
