### ISSUE TITLE
Proxy configuration dialogue is broken on Cytoscape 3.6.0 Windows

### ISSUE THREAD

**Issue by pbackx** [cytoscape/cytoscape#17]
When trying to configure the proxy settings from a fresh Cytoscape intall, it looks like the dialogue is not showing the required fields. No matter what option I choose from the dropdown, it's not showing me any fields:
![image](https://user-images.githubusercontent.com/358918/35730699-5a85852c-0813-11e8-87b4-950b950cb1d6.png)

However, after I manually enter the proxy properties proxy.server, proxy.server.port and proxy.server.type, the dialogue works as expected:
![image](https://user-images.githubusercontent.com/358918/35730760-9b1ba864-0813-11e8-9248-b746cf180a21.png)

Removing the proxy properties, again yields the first window without the necessary fields to fill in.

**Comment by AlexanderPico** [comment]
Thanks for reporting this. We are overhauling the property settings in v3.7.0. This will be fixed in that release.
