### ISSUE TITLE
network/view deletion

### ISSUE THREAD

**Issue by uludag** [cytoscape/cytoscape#20]
In order to delete a network/view I need to go to the control panel and right-click and select 'Destroy' options, i think this process could be made easier.

The word 'destroy' is also not commonly used, I am not sure but it may confuse first time users, 'delete' could be a better word?

**Comment by wlongabaugh** [comment]
Your point is well taken, though after discussion the core team recollects that "destroy" was chosen over "delete" after a lengthy debate to emphasize the non-recoverable nature of the operation, as there is no undo available.
 
Are there some other ways that we could make the process easier?

Thanks for the feedback.

**Comment by uludag** [comment]
I don't have any specific suggestions.

Cytoscape has _hide-selected-nodes-and-edges_ option but do not have an option to show selected nodes and edges only. I was using the _new-network-from-selection_ option to see selected nodes/edges in a new network when they are not visible in a crowded network. After viewing the network sometime I don't want to keep the network as part of my session, I thought deletion process could be improved.

Reactome Pathways App displays pathway networks with moveable/floating panels. They have commonly used Close icon (x) on the North-East corner of the diagram panel/windows. This makes closing of views easier, however Reactome app does not have the concept of deletion as the set of pathways/networks is fixed.
