### ISSUE TITLE
Issue to store images for github documentation

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape#6]
This "issue" is intended to serve as a store for images (i.e., to provide URL links for images) that are used in the README and wiki documents. These screenshots and such don't necessarily belong in the codebase, so we are using github issues to serve them up for github documentation usage. Feel free to "comment" with additional images here for this purpose. Simply, drag your image into a new comment, save the comment, then right-click on the image to `Copy image location`. This URL can then be used in other markdown docs.

**Comment by AlexanderPico** [comment]
<img width="706" alt="screen shot 2016-06-02 at 10 56 58 am" src="https://cloud.githubusercontent.com/assets/1418193/15755424/988d040a-28b1-11e6-88a8-9029d8b33329.png">

**Comment by AlexanderPico** [comment]
<img width="644" alt="screen shot 2016-06-02 at 11 10 08 am" src="https://cloud.githubusercontent.com/assets/1418193/15755663/a5c26c72-28b2-11e6-96c2-16651b76e9e3.png">

**Comment by AlexanderPico** [comment]
<img width="513" alt="screen shot 2016-06-02 at 11 19 34 am" src="https://cloud.githubusercontent.com/assets/1418193/15755974/09656990-28b4-11e6-96ad-d32a4abbcc66.png">

**Comment by AlexanderPico** [comment]
<img width="705" alt="screen shot 2016-06-02 at 11 20 08 am" src="https://cloud.githubusercontent.com/assets/1418193/15755985/1099ff64-28b4-11e6-8f1d-222b5e494fed.png">

**Comment by AlexanderPico** [comment]
<img width="219" alt="screen shot 2016-06-02 at 4 39 12 pm" src="https://cloud.githubusercontent.com/assets/1418193/15764559/94436324-28e0-11e6-85f0-9a4bd072f697.png">

**Comment by AlexanderPico** [comment]
![screen shot 2016-06-03 at 5 22 20 pm](https://cloud.githubusercontent.com/assets/1418193/15796483/2f63eb1c-29b3-11e6-8b74-a22969feb5f1.png)

**Comment by AlexanderPico** [comment]
![screen shot 2016-06-03 at 6 17 26 pm](https://cloud.githubusercontent.com/assets/1418193/15796685/b9ccafc4-29b7-11e6-8267-7cff561ca7a7.png)

**Comment by AdamStuart** [comment]
Looks like a temporary cache.  Still functional after close.
