### ISSUE TITLE
Is it possible to customize the path for configuration files dir?

### ISSUE THREAD

**Issue by JackieMium** [cytoscape/cytoscape#7]
I am running `Cytoscape-unix_3.4.0` on Debian.
I downloaded the `Cytoscape_3_4_0_unix.sh` and ran it in a terminal. The installation guide led me through the process and I chose the installation path of my own. However, a dir named `CytoscapeConfiguration` was made in my home dir. I tried looking for a option to customize configuration files path in the software but it was nowhere to find. 
Is it possible to customize configuration files path? 
If it's hard-coded and not changable, why not make it 'unix-style'? I mean, the common practice will be create a HIDDEN dir in one's home dir or put the configuration files dir in `~/.local` or `~/.config` or something like that.
Best regards.

**Comment by AlexanderPico** [comment]
Hi Jackie. Sorry for the late response. We routinely triage questions on our helpdesk (https://groups.google.com/forum/#!forum/cytoscape-helpdesk), redmine issue tracker, biostars and stackoverflow, but haven't been looking here... whoops!

We used to have a hidden config folder, but this caused many user issues when we needed to direct folks to certain files. Great majority of current user base is on Windows... then Mac... then Linux. So, that sets our style decisions.  

If you have followup questions, issues or suggestions, please post them on the helpdesk. Our team includes linux users so perhaps they will have more satisfactory answers than me :)
