### ISSUE TITLE
Hierarchial Layout with Angular Edges

### ISSUE THREAD

**Issue by dave7777** [cytoscape/cytoscape#8]
Hello!
I wonder if Cytoscape can arrange the nodes in the left-to-right hierarchial layout like is shown below:

<a href="http://tinypic.com?ref=icqp38" target="_blank"><img src="http://i65.tinypic.com/icqp38.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

I also need the edges to be in the same angled format (non-curvy).

Thank you!
Dave

**Comment by AlexanderPico** [comment]
Sure. First install yFiles layouts (option under the Layout menu). Then try the "yFiles Heirarchical Layout". Then open the rotation tool (View>Show Tool Panel) and rotate the network. The labels will remain "upright" so you can read them normally no matter how you rotate the network.

Protip: For a faster response, use the cytoscape helpdesk in the future: https://groups.google.com/forum/#!forum/cytoscape-helpdesk
