### ISSUE TITLE
RGB alpha value on node colors is not saved correctly

### ISSUE THREAD

**Issue by daniellobrunello** [cytoscape/cytoscape#9]
Using the discrete mapping function on a nodes fill color provides the possibility to adjust the alpha value for RGB. However, it is not correctly restored after re-opening the network. Instead it is set back to 255. 

Probably this is an issue at other parts too.
I'm using Cytoscape 3.5.1

**Comment by AdamStuart** [comment]
There is a separate property for Node transparency.  This is a conflict with keeping the alpha channel in RGBA.
